class obstacel{
    constructor(game,x){
        this.game=game;
        this.spritewidth=120;
        this.spriteheight=120;
        this.scaledwidth=this.scaledwidth*this.game.ratio;
        this.scaledheight=this.scaledheight*this.game.ratio;
        this.x=x;
        this.y=this.game.height*0.5-this.height;
    }
    resize(){
        this.scaledwidth=this.scaledwidth*this.game.ratio;
        this.scaledheight=this.scaledheight*this.game.ratio;
    }
    draw(){
        this.game.ctx.fillRect(this.x,this,y,this.scaledwidth,this.scaledheight);
    }
    update(){
this.x-=this.game.speed;
    }
}